Inmakes_Site/Home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about-us/', views.about, name='about'),
    path('internship/', views.internship, name='internship'),
]

Inmakes_Site/Inmakes_Site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('registration/', include('registration.urls')),
    path('pdetails/', include('pdetails.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_ROOT,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Inmakes_Site/pdetails/urls.py
from django.urls import path
from . import views

app_name = 'pdetails'

urlpatterns = [
    path('level/<int:id>', views.level, name='level'),
    path('level_sub/<int:id>', views.level, name='level_sub'),
    path('details/<int:id>/<int:lid>', views.details, name='details'),
    path('chapter-details/<int:lid>', views.chapter_details, name='sub_details'),
]

Inmakes_Site/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

Inmakes_Site/Home/models.py
from django.db import models


# Create your models here.
class Language(models.Model):
    language = models.CharField(max_length=250)
    
    def __str__(self):
        return '{}'.format(self.language)


class InternshipPrograms(models.Model):
    name = models.CharField(max_length=250, blank=False)
    image = models.ImageField(upload_to='images')
    lang = models.ForeignKey(Language, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.name)

Inmakes_Site/pdetails/models.py
from django.db import models
from Home.models import InternshipPrograms


# Create your models here.
class Level(models.Model):
    level = models.CharField(max_length=250)
    
    def __str__(self):
        return '{}'.format(self.level)


class Levelperprogram(models.Model):
    c_name = models.ForeignKey(InternshipPrograms, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    desc = models.TextField()
    
    def __str__(self):
        return '{}'.format(str(self.c_name) + str(self.level))


class Contents(models.Model):
    level_per_program = models.ForeignKey(Levelperprogram, on_delete=models.CASCADE)
    content_name = models.CharField(max_length=250)
    contents = models.FileField(upload_to='program_videos/')
    
    def __str__(self):
        return '{}'.format(str(self.level_per_program) + str(self.content_name))

Inmakes_Site/Home/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from registration.models import Profile

from .models import InternshipPrograms


# Create your views here.
def home(request):
    purchased_programs = Profile.objects.filter(user_id=request.user.id)
    print('programs :' ,purchased_programs)
    return render(request, 'home.html', {'purchased_programs': purchased_programs})


def contact(request):
    return render(request, 'contact.html')


def about(request):
    return render(request, 'aboutus.html')


def internship(request):
    if request.method == 'GET':
        language = request.GET.get('language')
        l_program = InternshipPrograms.objects.filter(lang=language)
    return render(request, 'internship.html', {'l_program': l_program})

Inmakes_Site/pdetails/views.py
from django.shortcuts import render
from .models import Levelperprogram, Contents
from Home.models import InternshipPrograms


# Create your views here.


def level(request, id):
    program = InternshipPrograms.objects.get(id=id)
    level = Levelperprogram.objects.filter(c_name=id)
    return render(request, 'level.html', {'level': level, 'program': program})


def details(request, id, lid):
    program = InternshipPrograms.objects.get(id=id)
    level = Levelperprogram.objects.filter(id=lid)
    return render(request, 'details.html', {'program': program, 'level': level})


def chapter_details(request, lid):
    contents = Contents.objects.filter(level_per_program_id=lid)
    return render(request, 'chapter_details.html', {'contents': contents})

Inmakes_Site/templates/Login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container mb-3 mt-3">
    <div class="card mb-3 mt-3" style="border-radius:10px;">
    <div class="row" style="margin-top:50px;margin-bottom:50px;">
            <div class="col-6">
                <img src="{% static 'image/login/Asset202.png' %}" alt="" width="500px;">
            </div>
            <div class="col-6">
                <form method="post">
                    {% csrf_token %}
                <h4 style="margin-bottom:20px;">Log in to your account</h4>
                <label for="email" style="margin-bottom:5px;">Email or Phone:</label><br>
                <input id="email" type="text" name="username" pattern="[^\s@]+@[^\s@]+\.[^\s@]+|\d+"  style="width:400px;margin-bottom:10px;height:40px;border-radius:10px;" ><br>
                <label for="password" style="margin-bottom:5px;">Password:</label><br>
                <input id="password" type="text" name="password" style="width:400px;margin-bottom:30px;height:40px;border-radius:10px;"><br>
                <button class="btn btn-success" type="submit" style="width:400px;margin-bottom:20px;height:40px;border-radius:10px;">Login</button>
                    <p>Forgot Password? <a href="{% url 'home:contact' %}" style="text-decoration:none;color:grey;"><b>Click here</b></a></p>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container" style="padding-top:50px;margin-bottom:50px;">
    <div class="card" style="background-color:#43D477;height:150px;border-radius:15px;">
            <div class="col-12">
                <div class="row">
                    <div class="col-6"  style="padding-left:30px;padding-top:50px;">
                        <p style="font-size:30px;color:white;"><b>Join with us now</b></p>
                        <p>For Support - 04842998191</p>
                    </div>
                    <div class="col-6" style="text-align:right;padding-right:30px;padding-top:60px;">
                        <form>
                        <input style="width:80%;height:50px;border-radius:15px;position:relative;" type="email" name="email" placeholder="Enter your email here">
                        <button style="text-align:center;margin-top:5px;border-radius:15px;background-color:#43D477;color:white;height:40px;width:80px;position:absolute;top:60px;right:25px;z-index:2;">Join</button>
                        </form>
                    </div>
                </div>
            </div>
    </div>
</div>

{% endblock %}

Inmakes_Site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block body %}
{% endblock %}
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<script>
    const swiper = new Swiper('.swiper',{

        autoplay:{
            delay: 3000,
            disableOnInteraction:false,
            },
    loop: true,
    pagination:{
        el:'.swiper-pagination',
        clickable:true,
    },
});

$(function() {
  $('.btn').click(function() {
    $(this).toggleClass('is-clicked');
  });
});

</script>
</body>
</html>

Inmakes_Site/templates/chapter_details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="w3-bar w3-black mb-3 mt-3" style="background-color:#43D477;height:50px;border-radius:10px;display:flex;justify-content:space-between;">
                <div style="color:white;margin-top:15px;margin-left:20px;">
                    <label><b>Classes</b></label>
                </div>
            </div>
            <h6>Module Contents</h6><hr>
            <P style="margin-left:50px;">Title</P>
            <br>
            {% for i in contents %}
            <ol>
                <li>
                    <div class="card">
                        <div style="margin-left:20px;display:flex;justify-content:space-between;margin-top:10px;margin-bottom:10px;">
                            <div>
                               {{i.content_name}}
                            </div>
                             <div style="margin-right:20px;">
                                <a href="{{i.contents.url}}"><button class="btn btn-success" style="width:150px;">Play</button></a>
                            </div>
                        </div>
                    </div>
                </li>
            </ol>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Inmakes_Site/templates/footer.html
{% load static %}
<footer>
   <div class="fluid-container footer-container">
       <div class="container">
           <div class="row">
              <div class="col-3">
                <img src="{% static 'image/logo1.png' %}" width="250px;">
                  <p class="footer_text">Learn new skills with top educators. Inmakes Learning hub is the right place for you to learn new skills that will fetch you better opportunities in your career.</p>
              </div>
               <div class="col-2">
                    <p class="footer_text">Additional Links</p>
                   <ul class="footer_text">
                       {% if user.is_authenticated %}
                       <li><a href="{% url 'registration:logout' %}" style="text-decoration:none;color:white;" class="footer_links">Logout</a></li>
                       {% else %}
                        <li><a href="{% url 'registration:login' %}" style="text-decoration:none;color:white;" class="footer_links">Login</a></li>
                       <li><a href="{% url 'registration:register' %}" style="text-decoration:none;color:white;" class="footer_links">Register</a></li>
                       {% endif %}

                       <li><a href="{% url 'home:about' %}" style="text-decoration:none;color:white;" class="footer_links">About</a></li>
                       <li><a href="{% url 'home:contact' %}" style="text-decoration:none;color:white;" class="footer_links">Contact Us</a></li>
                   </ul>
               </div>
               <div class="col-3">
                    <p class="footer_text">Support</p>
                   <a href="tel: +91 4842998191" style="text-decoration:none"><p style="color:white;"><span>&#9743;</span> +91 4842998191</p></a>
                   <a href="mailto:mail@inmakeslh.com" style="text-decoration:none"><p style="color:white;"><span>&#128231;</span> mail@inmakeslh.com</p></a>
               </div>
               <div class="col-4">
                    <p class="footer_text">Recognized/Certified by</p>
                   <img src="{% static 'image/Group201353.png' %}" width="75px;">
                   <img src="{% static 'image/Group201354.png' %}" width="75px;">
                   <img src="{% static 'image/Group 1355.png' %}" width="150px;">
                        <a href=""><i class="fa-solid fa-instagram"></i></a>
                        <a href=""><i class="fa-solid fa-whatsapp"></i></a>
                       <a href=""><i class="fa-solid fa-youtube"></i></a>
                       <a href=""><i class="fa-solid fa-linkedin"></i></a>
                       <a href=""><i class="fa-solid fa-facebook"></i></a>
               </div>
           </div>
           <hr style="color:green;height:3px;">
       <P style="text-align:center;color:white;">&copy; Inmakes Learning Hub ; This is a dummy site made for practice.</P>
       </div>
    </div>
</footer>

Inmakes_Site/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
  <div class="row hero">
    <div class="col-12 col-md-6 colhero">
      <div>
        <h2 class="skillUp" style="font-size:50px;padding-top:100px;">SkillUp Now</h2>
        <p class="skillUp" style="font-size:25px;padding-top:20px;"><strong>India's No.1 Virtual Internship Platform</strong></p>
        <p style="font-size:25px;padding-top:10px;">Learn today <br> for a better tomorrow</p><br>
        <a href="tel: +91 4842998191"><button class="btn btn-success trainerbtn">Connect With Trainer</button></a>
      </div>
    </div>
    <div class="col-12 col-md-6 colheroimage">
      <img src="{% static 'image/right-top.png' %}" class="img-fluid" alt="Right Top Image">
    </div>
  </div>
</div>
<div class="container">
  <div class="row" style="padding-top:30px;">
    <div class="col-12 choose">
      <h3 style="font-family:Montserrat,sans-serif;font-size:25px;font-weight:700;"><u style="text-decoration-color:green;">WHY</u> CHOOSE US</h3>
    </div>
    <div class="col-6 col-md-3" style="padding-top:30px;">
      <div class="shadow card mb-3">
        <img src="{% static 'image/One-to-one.png' %}" width="80px;" class="mx-auto d-block" style="padding-top:20px">
        <div class="card-body">
          <h5 class="card-title" style="text-align:center">Professional Training</h5>
          <p class="card-text" style="text-align:center">One-to-one mentorship from Experts</p>
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3" style="padding-top:30px;">
      <div class="shadow card mb-3">
        <img src="{% static 'image/Challenge.png' %}" width="80px;" class="mx-auto d-block" style="padding-top:20px">
        <div class="card-body">
          <h5 class="card-title" style="text-align:center">Gain work-experience</h5>
          <p class="card-text" style="text-align:center">Challenge and Task-based learning</p>
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3" style="padding-top:30px;">
      <div class="shadow card mb-3">
        <img src="{% static 'image/Placement.png' %}" width="80px;" class="mx-auto d-block" style="padding-top:20px">
        <div class="card-body">
          <h5 class="card-title" style="text-align:center">Great Career</h5>
          <p class="card-text" style="text-align:center">100% Life-long Placement Assistance</p>
        </div>
      </div>
    </div>
    <div class="col-6 col-md-3" style="padding-top:30px;">
      <div class="shadow card mb-3">
        <img src="{% static 'image/Time.png' %}" width="80px;" class="mx-auto d-block" style="padding-top:20px">
        <div class="card-body">
          <h5 class="card-title" style="text-align:center">Quality Classes</h5>
          <p class="card-text" style="text-align:center">Live Online sessions & flexible timing</p>
        </div>
      </div>
    </div>
    </div>
</div>
<div class="container slider_container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="swiper">
        <div class="swiper-wrapper">
          <div class="swiper-slide"><img src="{% static 'image/Challenges.jpg' %}"></div>
          <div class="swiper-slide"><img src="{% static 'image/HR.jpg' %}"></div>
          <div class="swiper-slide"><img src="{% static 'image/Language.jpg' %}"></div>
        </div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="swiper">
        <div class="swiper-wrapper">
          <div class="swiper-slide"><img src="{% static 'image/One20to20One.jpg' %}"></div>
          <div class="swiper-slide"><img src="{% static 'image/Swapping.jpg' %}"></div>
          <div class="swiper-slide"><img src="{% static 'image/Timing.jpg' %}"></div>
        </div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
  </div>
</div>

<!--User subscribed Program portion-->
{% if user.is_authenticated %}
<div class="container">
  <div class="row" style="padding-top:30px;">
    <div class="col-12 choose">
      <h3 style="font-family:Montserrat,sans-serif;font-size:25px;font-weight:700;"><u style="text-decoration-color:green;">Subscribed</u>&nbsp Subjects</h3>
    </div>
    <p class="choose" style="font-family:Montserrat,sans-serif;font-size:20px;font-weight:500;">browse subscribed subjects and materials here</p>
      <div class="row" style="display:flex;justify-content:left;">
        {% for i in purchased_programs %}
            <div class="col-lg-2 col-md-3 col-sm-4 mb-3" style="padding-top:20px;">
                <div class="shadow cards h-100" style="border-radius:15px;">
                <a href="{% url 'pdetails:level_sub' i.program.id %}"><img class="card-img-top" src="{{ i.program.image.url }}" width="50px;" style="background-color:black;"></a>
                    <div class="card-body">
                        <div class="card-title text-center">{{i.program.name}}</div>
                    </div>
                </div>
            </div>
    {% endfor %}
      </div>
              {% for i in messages %}
            {{i}}
          {% endfor %}
  </div>
</div>
{% endif %}
<!--All Program portion-->

<div class="container">
  <div class="row" style="padding-top:30px;">
    <div class="col-12 choose">
      <h3 style="font-family:Montserrat,sans-serif;font-size:25px;font-weight:700;"><u style="text-decoration-color:green;">Trending</u>Programs</h3>
    </div>
    <p class="choose" style="font-family:Montserrat,sans-serif;font-size:20px;font-weight:500;">Choose your Internship Programs</p>
      <div class="row" style="display:flex;justify-content:left;">
         {% for i in program %}
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6 mb-3" style="padding-top:20px;">
            <div class="shadow cards h-100" style="border-radius:15px;">
                <a href="{% url 'pdetails:level' i.id %}"><img class="card-img-top" src="{{ i.image.url }}" width="50px;" style="background-color:black;"></a>
                <div class="card-body">
                    <div class="card-title text-center">{{i.name}}</div>
                </div>
            </div>
        </div>
        {% endfor %}
      </div>
  </div>
</div>

 <!-- feedback -->

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="choose" style="padding-top:60px;"><u style="text-decoration-color:green;">Testimonials</u></h3>
        </div>
        <p class="choose" style="font-family:Montserrat,sans-serif;font-size:20px;font-weight:500;">What our students say about this</p>
        <div class="container slider_container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="swiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as1.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as2.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as3.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as4.png' %}"></div>
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="swiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as5.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as6.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as7.png' %}"></div>
                            <div class="swiper-slide"><img src="{% static 'image/feedback/as8.png' %}"></div>
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fluid-container" style="margin-bottom:20px;">
    <div class="row" style="text-align:center;">
        <div style="position:relative;">
            <div style="position:absolute; top:25%; left:0; right:0;bottom:auto; height:250px; background-color:grey;"></div>
            <div style="position:relative; z-index:1; display:flex; flex-direction: column; align-items: center;">
                <a href="https://youtu.be/399CdeCOLtg"><img src="{% static 'image/icons/btn-play.png' %}" style="position:absolute;right:45%;top:25%;width:100px;height:100px;border-radius:100px;border-color:white;"> </img></a>
                <p style="position:absolute;right:auto;top:75%; margin: 0; text-align: center;font-size:25px;color:white;"><b>Kick Start Your Career today with Inmakes! </b><br>Get standard industrial exposure without any limitations.</p>
                <img src="{% static 'image/vids.png' %}">
            </div>
        </div>
    </div>
</div>
<!-- Collaborations -->
<div class="container" style="padding-bottom:50px;">
    <div class="row">
        <div class="col-12">
            <h3 class="choose" style="padding-top:60px;"><u style="text-decoration-color:green;">Collaborations</u></h3>
        </div>
        <p class="choose" style="font-family:Montserrat,sans-serif;font-size:20px;font-weight:500;padding-bottom:20px;">5000+ hiring partner companies</p>
        <div class="col-lg-2 col-md-4 col-sm-6">
            <img src="{% static 'image/collaborations/1.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6" style="aspect-ratio:3/2;">
            <img src="{% static 'image/collaborations/2.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6" style="aspect-ratio:3/2;">
            <img src="{% static 'image/collaborations/3.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6" style="aspect-ratio:3/2;">
            <img src="{% static 'image/collaborations/4.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6" style="aspect-ratio:3/2;">
            <img src="{% static 'image/collaborations/5.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
            <img src="{% static 'image/collaborations/6.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
            <img src="{% static 'image/collaborations/7.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
            <img src="{% static 'image/collaborations/8.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
            <img src="{% static 'image/collaborations/10.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
           <img src="{% static 'image/collaborations/11.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain">
        </div>
        <div class="col-lg-2 col-md-4 col-sm-6">
           <a href="{% static 'pdf/Tie up Companies 2022 HQ.pdf' %}"><img src="{% static 'image/collaborations/12.png' %}" width="100px;" height="100;" style="aspect-ratio:3/2;object-fit:contain"></a>
        </div>
        </div>
    </div>
{% endblock %}

Inmakes_Site/templates/internship.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="fluid-container"  style="background-image:url('/static/image/about/backdrop.png');">
   <div class="container mb-3">
        <div class="row" style="padding-top:30px;">
            <h3 style="font-family:Montserrat,sans-serif;font-size:25px;font-weight:700;text-align:center;"><u style="text-decoration-color:green;">Trending</u>Programs</h3>
            {% if l_program %}
            <div class="col-9">
                <div class="row">
                    {% for i in l_program %}
                    <div class="col-4" style="padding-top:20px;padding-right:20px;">
                        <div class="shadow cards intern-card h-100" style="border-radius:15px;">
                            <img  class="card-img-top" src="{{ i.image.url }}" width="50px;" style="background-color:black;">
                            <div class="card-body">
                                <div class="card-title"  style="display:flex;justify-content:center;text-align:center;"><b>{{i.name}}</b></div>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'pdetails:level' i.id %}"><button class="btn btn-success btn-sm float-center" style="text-align:center;">View Details</button></a>
                                <p>to know more</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
            {% else %}
            <div class="col-9">
                <div class="row" style="display:flex;justify-content:left;">
                {% for i in program %}
                    <div class="col-4" style="padding-top:20px;padding-right:20px;">
                        <div class="shadow card h-100" style="border-radius:15px;">
                            <img  class="card-img-top" src="{{ i.image.url }}" width="50px;" style="background-color:black;">
                            <div class="card-body">
                                <div class="card-title"  style="display:flex;justify-content:center;text-align:center;"><b>{{i.name}}</b></div>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'pdetails:level' i.id %}" ><button class="btn btn-success btn-sm float-center" style="text-align:center;">View Details</button></a>
                                <p>to know more</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
            {% endif %}
        <div class="col-3">
            <div class="shadow cards" style="border-radius:20px;">
                <div class="card-body">
                    <div class="card-title">
                        <h6 style="text-align:center;font-size:20px;"><u style="text-decoration-color:green;text-decoration-thickness:1px;">Langu</u>ages</h6>
                    </div>
                    <div class="card-text">
                        <form method="GET">
                            <div style="padding-bottom:20px;">
                                {% for i in language %}
                                <label for="lan" >{{i.language}}</label>
                                <div style="text-align:right;">
                                    <input type="radio" name="language" id="lan" value="{{i.id}}" style="width:30px;"><br>
                                </div>
                                {% endfor %}
                            </div>
                            <div style="text-align:center;">
                                <button class="btn btn-success mb-3" type="submit" style="width:120px;">Filter</button><br>
                                <a href="{% url 'home:internship' %}"><button class="btn btn-secondary mb-3"  style="width:120px;">All Programs</button></a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

Inmakes_Site/templates/level.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="banner" style="background-image:url('/static/image/pdetails/category_cover1.jpg');min-height:190px;" >
    {% if program %}
    <h4 style="color:white;text-align:center;padding-top:30px;">{{program.name}}</h4>
    {% endif %}
</div>
<div class="container">
    <div class="row" style="display:flex;justify-content:left;">
        {% for i in level %}
        <div class="col-4">
            <div class="shadow card mb-3 mt-3" style="width: 18rem;border-radius:10px;">
            {% if program %}
                {% if 'level_sub' in request.path %}
                <a href="{% url 'pdetails:sub_details' i.id %}"><img class="card-img-top" src="{{ program.image.url }}" alt="Card image cap"></a>
                {% else %}
                <a href="{% url 'pdetails:details' program.id i.id %}"><img class="card-img-top" src="{{ program.image.url }}" alt="Card image cap"></a>
                {% endif %}
            {% endif %}
                <div class="card-body" style="background-color:#43D477;">
                    <h5 class="card-title" style="text-align:center;">{{i.level}}</h5>
                    <p class="card-text" style="text-align:center;"><b>{{i.c_name.name}}</b></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

Inmakes_Site/templates/navbar.html
{% load static %}
<nav  class="navbar navbar-extends-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href=""><img src="{% static 'image/inmakelogo.png' %}"></a>
        <button class="btn btn-transparent"><a class="navbar-brand" href="{% url 'home:home' %}">Home</a></button>
        <button class="btn btn-transparent"><a class="navbar-brand" href="{% url 'home:internship' %}">Internship</a></button>
        <button class="btn btn-transparent"><a class="navbar-brand" href="{% url 'home:about' %}">About</a></button>
        <button class="btn btn-transparent"><a class="navbar-brand" href="{% url 'home:contact' %}">Contact</a></button>
        {% if user.is_authenticated %}
        <button class="btn btn-success"><a class="navbar-brand" href="{% url 'registration:logout' %}" style="color:white;">Logout</a></button>
        {% else %}
        <button class="btn btn-success"><a class="navbar-brand" href="{% url 'registration:register' %}" style="color:white;">Register</a></button>
        <button class="btn btn-success"><a class="navbar-brand" href="{% url 'registration:login' %}" style="color:white;">Login</a></button>
        {% endif %}
    </div>
</nav>